blank_issues_enabled: false
contact_links:
  - name: Storyblok Help Center/Service Desk - official support channel
    url: https://storyblok.atlassian.net/servicedesk/customer/portals
    about: You can raise a request for Storyblok Service Desk.
    
  - name: Discord community - no official support is provided via Discord
    url: https://discord.gg/WmMYYQp
    about: You can reach out to Storyblok Discord community.
